name: Test grammar

on:
  push:
    branches: [master]
    paths:
      - "scripts.js"
      - "common/*"
      - "*/grammar.js"
      - "*/src/**"
      - "bindings/**"
      - "binding.gyp"
  pull_request:
    paths:
      - "scripts.js"
      - "common/*"
      - "*/grammar.js"
      - "*/src/**"
      - "bindings/**"
      - "binding.gyp"

jobs:
  test:
    uses: tree-sitter-grammars/.github/.github/workflows/ci.yml@main
    with:
      test-library: true
  fuzz:
    name: Fuzz parsers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [xml, dtd]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fuzz ${{matrix.language}} parser
        uses: tree-sitter-grammars/tree-sitter-fuzz-action@v2
        with:
          directory: ${{matrix.language}}
